ALTER TABLE public.watchlist ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT 'movie';
ALTER TABLE public.watchlist ADD COLUMN IF NOT EXISTS year TEXT NOT NULL DEFAULT '';
ALTER TABLE public.watchlist ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT '';
